GCC-13 - добавила react router
team-learning-yandex-praktikum/game-learning-project pull request #1
Opened 2024-03-11 16:28 UTC by AnastasiaKurochkina

### Какую задачу решаем

### Скриншоты/видяшка (если есть)

### TBD (если есть)

2024-03-11 17:51 UTC, ISAYwtf commented on package-lock.json
Этот файл лишний. В этом проекте используем `yarn`, поэтому переустанови заново зависимости через него

2024-03-11 18:03 UTC, ISAYwtf commented
В тесте `App.test` оберни компонент `<App />` в `BrowserRouter`, чтобы прошли тесты в проверках

2024-03-11 18:05 UTC, ISAYwtf requested changes

2024-03-11 18:05 UTC, ISAYwtf commented on packages/client/src/pages/Forum/index.ts
> +export { Forum as default } from './Forum'
Можно так сделать. Можешь по желанию исправить, но необязательно
```suggestion
export { default } from './Forum'
```

2024-03-11 18:25 UTC, LeylaBR commented on packages/client/src/App.tsx
> +  const route = useRoutes(routes)
можно назвать не route а например renderRoutes просто их же много или routes а константу routesMap

2024-03-11 18:30 UTC, LeylaBR commented on packages/client/src/pages/Forum/index.ts
> +export { Forum as default } from './Forum'
export { default } from './Forum' если я не ошибаюсь, но при условии что сам компонент Forum будет экспортирован тоже по дефолту. Типа 
const Forum =() => {
  return <h1>Forum</h1>
}
export default Forum 
Ну это заглушки, походу подправим

2024-03-11 18:38 UTC, ISAYwtf commented on packages/client/src/App.tsx
> +  const route = useRoutes(routes)
Да, можно кстати просто `router` или `renderRouter`. А для массива подошло бы `routesConfig`

2024-03-11 18:41 UTC, ISAYwtf commented on packages/client/src/pages/Forum/index.ts
> +export { Forum as default } from './Forum'
А, да, не обратил внимание, что там именованный экспорт.

2024-03-12 17:35 UTC, ISAYwtf approved these changes

2024-03-13 05:58 UTC, merged