GСС-32 Сверстать страницу пользователя
team-learning-yandex-praktikum/game-learning-project pull request #16
Opened 2024-03-18 20:57 UTC by AnastasiaKurochkina

Добавила страницу пользователя (компонент с просмотром информации, компонент редактирования основной информации, компонент редактирования пароля). Добавила компонент загрузки аватара пользователя. Добавила валидацию на изменение пароля. Подключила API для изменения основной информации, пароля и аватара.

2024-03-19 11:52 UTC, ISAYwtf commented on packages/client/src/components/Avatar/Avatar.tsx
> +import { updateAvatar } from '@/services/profile'
```suggestion
import { updateAvatar } from '@services/profile'
```

2024-03-19 11:52 UTC, ISAYwtf commented on packages/client/src/components/Avatar/Avatar.tsx
Мне кажется это слишком специфичный компонент, чтобы держать его в общих компонентах. Стоит перенести в `Profile/elements`

2024-03-19 11:52 UTC, ISAYwtf commented on packages/client/src/components/Form/Form.tsx
> +                SubmitButtonProps?.onClick ? e.preventDefault() : undefined
Вообще концептуально так делать не очень хорошо, так как это кнопка сабмита и отключать функцию сабмита лучше через `type`, да и не всегда при передаче собственного обработчика может быть ситуация, когда нужно отключить сабмит. 

А если удобнее preventDefault, то лучше это в своем обработчике вызывать

2024-03-19 11:52 UTC, ISAYwtf commented on packages/client/src/pages/Profile/elements/ProfileInfo/ProfileInfo.tsx
> +import { updateProfile } from '@/services/profile'
```suggestion
import { updateProfile } from '@services/profile'
```

2024-03-19 11:52 UTC, ISAYwtf commented on packages/client/src/pages/Profile/elements/ProfileInfo/ProfileInfo.tsx
> +      setIsLoading(false)
Включать/Отключать состояния загрузки лучше в функции самой загрузки, в данном случае `fetchAvatar`.
В начале функции `setIsLoading(true)`, а в конце после загрузки `setIsLoading(false)` (желательно в блоке `finally`)

2024-03-19 11:52 UTC, ISAYwtf commented on packages/client/src/pages/Profile/elements/ProfileInfo/ProfileInfo.tsx
> +      if (userData) {
Тут два момент которые стоит поправить:
1. Лучше избегать вложенностей - в данном случае можно в начале поставить `if (!userData) { return }`;
2. Не хватает try...catch для обработки ошибок

2024-03-19 11:52 UTC, ISAYwtf commented on packages/client/src/pages/Profile/elements/ProfileInfo/ProfileInfo.tsx
> +        if ('avatar' in userData && userData.avatar) {
```suggestion
        if (userData?.avatar) {
```

2024-03-19 11:52 UTC, ISAYwtf commented on packages/client/src/pages/Profile/elements/ProfileInfo/ProfileInfo.tsx
> +    return <></>
Кстати нужно будет потом подумать над компонентом `Loader`, но не сейчас конечно

2024-03-19 11:52 UTC, ISAYwtf commented on packages/client/src/pages/Profile/elements/ProfileInfo/ProfileInfo.tsx
> +          variant: 'outlined',
```suggestion
          variant: editMode ? 'contained' : 'outlined',
```

2024-03-19 11:52 UTC, ISAYwtf commented on packages/client/src/pages/Profile/elements/ProfilePassword/ProfilePassword.tsx
> +import { updatePassword } from '@/services/profile'
```suggestion
import { updatePassword } from '@services/profile'
```

2024-03-19 11:52 UTC, ISAYwtf commented on packages/client/src/services/profile.ts
Не уверен, что папка с сервисами нам понадобится после подключения стора, но посмотрим

2024-03-19 11:52 UTC, ISAYwtf commented on packages/client/src/utils/validation/validators.ts
> +export const validateRepeatedNewPassword = (
Чтобы не дублировать функции, лучше сделать так, чтобы функция принимала две строки и в конфиге сразу передавать из values нужное значение
```suggestion
export const validateRepeatedNewPassword = (password: string, secondPassword: string) => {
```

2024-03-19 11:52 UTC, ISAYwtf commented on packages/client/src/utils/validation/validators.ts
> +  return validatePassword(password)
```suggestion
  return validatePassword(password) ?? (
    password === values.old_password 
      ? ERRORS.equalsPassword 
      : undefined
    )
```

2024-03-19 11:52 UTC, ISAYwtf commented on packages/client/src/utils/validation/validationConfig.ts
> +    minLength: { value: 8, message: getMinLengthError(8) },
Эта часть дублируется 3 раза. Стоит вынести этот объект как `validationPasswordConfig` и применять для всех паролей

2024-03-19 11:57 UTC, ISAYwtf commented
Еще важный момент. В твоей ветке очень много лишних коммитов, должен быть один (ну или как минимум только те, что ты сделала сама, но желательно на один PR один коммит). Судя по всему ты для подтягивания изменений из main пользуешься `merge`. Для этого лучше использовать `rebase`, так как тебе не нужно объединять ветки, а только обновить текущую. Тогда история коммитов будет чище.

2024-03-19 16:23 UTC, LeylaBR commented on packages/client/src/pages/Profile/elements/ProfileInfo/ProfileInfo.tsx
> +  const [isLoading, setIsLoading] = useState(true)
если протипизированы все стейты то нужно и нижний

2024-03-19 16:28 UTC, LeylaBR commented on packages/client/src/pages/Profile/elements/ProfileInfo/ProfileInfo.tsx
> +  const [isLoading, setIsLoading] = useState(true)
const [avatarUrl, setAvatarUrl] = useState<string | undefined>(undefined)  Здесь нужен undefined? Hиже присваивается или аватар или путая строка, возможно проще первоначально установить "". И тогда можно не типизировать стейты, ts сам определяет примитивные типы

2024-03-19 20:24 UTC, ISAYwtf approved these changes

2024-03-20 08:45 UTC, kate-lozovaya requested changes
Оставила комментарии. Посмотри их и призывай меня к ревью, как везде ответишь. И можешь добавить меня в репозиторий, чтобы у меня появилась возможность ставить `resolve` на открытые `issue`.

И еще из комментариев не конкретно к этому ПР, а в целом. Обычно `css` оформляется в `kebab-case`, а в `tsx` файлах классы записываются как `camelCase`. Конвертацию можно настроить на уровне сборщика, но у меня есть опыт только с `webpack`, не знаю, сложно ли сделать тоже самое в `vite`. Но будет здорово, если вы сможете сделать эту задачу )

2024-03-20 08:45 UTC, kate-lozovaya commented on packages/client/src/components/Form/Form.tsx
> +              disabled={SubmitButtonProps.disabled ?? !isValid}
[Вопрос]
Почему переменная названа с большой буквы?
В `js` обычно переменные в `camelCase`

2024-03-20 08:45 UTC, kate-lozovaya commented on packages/client/src/pages/Profile/type.ts
> +export enum TabProfile {
[Предложение]
Интернет советует использовать `PascalCase` для ключей в `enum`
То есть тут лучше `ProfileInfo = 'profileInfo'` написать

2024-03-20 08:45 UTC, kate-lozovaya commented on packages/client/src/pages/Profile/Profile.tsx
> +      {currentTab === TabProfile.profileExit && <ProfileExit />}
[Предложение]
Здесь все условия взаимноисключающие, но с таким условным рендерингом эта логика теряется.

Тут можно использовать отдельный компонент или функцию рендера, если считаешь, что на компонент не тянет, со `switch`. Но мне больше нравится делать объект вне компонента, чтобы не было пересозданий при ререндере, вот так:
```ts
const tabContent: Record< TabProfile, ReactNode> = {
  [TabProfile.profileInfo]: <ProfileInfo />,
  [TabProfile.profilePassword]: <ProfilePassword />,
  [TabProfile.profileExit]: <ProfileExit />
}
``` 

И тогда тут можно будет просто взять значение из объекта
```suggestion
      {tabContent[currentTab]}
```

2024-03-20 08:45 UTC, kate-lozovaya commented on packages/client/src/pages/Profile/elements/Avatar/Avatar.tsx
> +  const [avatarProfile, setAvatar] = useState<string>(avatar ? avatar : '')
[Исправление]
Можно сократить запись, если использовать оператор `??`, логика не изменится, будет пустая строка, если `avatar` - `null` или `undefined`, в остальных случаях - `avatar`
```suggestion
  const [avatarProfile, setAvatar] = useState<string>(avatar ?? '')
```

2024-03-20 08:45 UTC, kate-lozovaya commented on packages/client/src/pages/Profile/elements/Avatar/Avatar.tsx
> +  }
[Исправление]
Оберни функцию в `useCallback`, чтобы она не пересоздавалась на ререндр

2024-03-20 08:45 UTC, kate-lozovaya commented on packages/client/src/pages/Profile/elements/Avatar/Avatar.tsx
> +          : styles.avatarBackground
[Исправление]
Условия с отрицанием читаются сложнее, тут лучше от него избавиться
```suggestion
        avatarProfile
          ? styles.avatarBackground
          : styles.avatarBackgroundDefault
```

2024-03-20 08:45 UTC, kate-lozovaya commented on packages/client/src/pages/Profile/elements/Avatar/Avatar.tsx
> +        src={avatarProfile ? avatarProfile : AvatarImage}
[Исправление]
Замени тернарный оператор на нулевое слияние `??`

2024-03-20 08:45 UTC, kate-lozovaya commented on packages/client/src/pages/Profile/elements/Avatar/Avatar.tsx
> +        className={styles.avatarImage}></img>
[Исправление]
Тут не нужен закрывающий тег. 
Желательно добавить в линтер правило, которое будет автоматически убирать все лишние закрывающие теги, но это нужно сделать отдельной задачей, не в этом ПР
```suggestion
        className={styles.avatarImage} />
```

2024-03-20 08:45 UTC, kate-lozovaya commented on packages/client/src/pages/Profile/elements/Avatar/avatar.module.css
> +  background: rgb(26, 26, 26);
[Вопрос]
В этом же файле используются переменные для цветов. Может и этот цвет получится вынести в переменную?

2024-03-20 08:45 UTC, kate-lozovaya commented on packages/client/src/pages/Profile/elements/ProfileExit/ProfileExit.tsx
> +  }
[Исправление]
Оберни в `useCallback`, чтобы функция не пересоздавалась на ререндр

2024-03-20 08:45 UTC, kate-lozovaya commented on packages/client/src/pages/Profile/elements/ProfileInfo/ProfileInfo.tsx
> +  const toggleEditMode = (e?: React.MouseEvent<HTMLButtonElement>) => {
[Исправление]
Оберни функции в useCallback

2024-03-20 08:45 UTC, kate-lozovaya commented on packages/client/src/pages/Profile/elements/ProfileInfo/ProfileInfo.tsx
> +  const [editMode, setEditMode] = useState(false)
[Предложение]
Обычно для булевых значение используется `is` или `has`. 
Тут по названию непонятно, что значение будет булево. Может добавить `is`?
```suggestion
  const [isEditMode, setIsEditMode] = useState(false)
```

2024-03-20 08:45 UTC, kate-lozovaya commented on packages/client/src/pages/Profile/elements/ProfileInfo/ProfileInfo.tsx
> +    data: Omit<UserDTO, 'id' | 'display_name' | 'avatar'>
[Вопрос]
Почему не `camelCase` для переменной? 
Если это данные с бека, можно написать для них маппер, чтобы на фронте использовать данные в удобном виде

2024-03-20 08:45 UTC, kate-lozovaya commented on packages/client/src/pages/Profile/elements/ProfileInfo/ProfileInfo.tsx
> +        if ('avatar' in userData && userData.avatar) {
[Исправление]
Тут не нужно проверять наличие ключа в объекте. Если `avatar` нет в `userData`, то `userData.avatar` будет `undefined`
```suggestion
        if (userData.avatar) {
```

2024-03-20 08:45 UTC, kate-lozovaya commented on packages/client/src/pages/Profile/elements/ProfileInfo/ProfileInfo.tsx
> +    return <></>
[Предложение]
Может тут слово `Loading` написать, если пока нет компонента лоадера? А то пустая страница может запутать и напугать пользователя

2024-03-20 08:45 UTC, kate-lozovaya commented on packages/client/src/pages/Registration/Registration.tsx
> +      fields={omit(fieldsConfig, [
[Вопрос]
Точно ли тут нужен `omit`? в документации указано, что он значительно медленнее `pick` `Note: This method is considerably slower than [_.pick](https://lodash.com/docs/#pick).`
Есть какие-то предубеждения про `lodash`, что он делает все медленным)

2024-03-20 08:45 UTC, kate-lozovaya commented on packages/client/src/utils/validation/validationConfig.ts
> +  maxLength: { value: 40, message: getMaxLengthError(40) },
👍🏻

2024-03-20 09:03 UTC, ISAYwtf commented on packages/client/src/components/Form/Form.tsx
> +              disabled={SubmitButtonProps.disabled ?? !isValid}
Если речь про SubmitButtonProps, то это не является переменной, это пропс - объект с пропсами для внутренних компонентов. Дизайн-системы иногда пользуются таким приемом, чтобы дать пользователю понять, какой именно пропс позволяет передать объект свойств тому или иному компоненту. То есть если пропс начинается с большой буквы, значит он принимает набор пропсов для какого-то компонента.
На практике это очень удобно.

2024-03-20 21:15 UTC, kate-lozovaya commented on packages/client/src/components/Form/Form.tsx
> +              disabled={SubmitButtonProps.disabled ?? !isValid}
ок
Но выглядит совсем непривычно )

2024-03-20 21:18 UTC, kate-lozovaya commented on packages/client/src/pages/Profile/elements/Avatar/avatar.module.css
> +  background: rgb(26, 26, 26);
тут нет ответа

2024-03-20 21:19 UTC, kate-lozovaya commented on packages/client/src/pages/Profile/elements/ProfileInfo/ProfileInfo.tsx
> +    data: Omit<UserDTO, 'id' | 'display_name' | 'avatar'>
тут нет ответа

2024-03-20 21:20 UTC, kate-lozovaya commented on packages/client/src/pages/Registration/Registration.tsx
> +      fields={omit(fieldsConfig, [
тут нет ответа

2024-03-20 21:21 UTC, kate-lozovaya reviewed
по трем комментариям нет ничего в коде и ответов там тоже нет. Ответь на них, пожалуйста

2024-03-21 05:28 UTC, AnastasiaKurochkina commented on packages/client/src/pages/Profile/elements/Avatar/avatar.module.css
> +  background: rgb(26, 26, 26);
Этот цвет используется только в этом компоненте, поэтому, мне кажется, нет смысла выносить. Вынесены именно переиспользуемые цвета.

2024-03-21 05:28 UTC, AnastasiaKurochkina commented on packages/client/src/pages/Registration/Registration.tsx
> +      fields={omit(fieldsConfig, [
Мне кажется, что в данной ситуации что pick, что omit будут примерно одинаково отрабатывать)

2024-03-21 05:28 UTC, AnastasiaKurochkina commented on packages/client/src/pages/Profile/elements/ProfileInfo/ProfileInfo.tsx
> +    data: Omit<UserDTO, 'id' | 'display_name' | 'avatar'>
Мы решили это сделать после добавления стора

2024-03-21 13:59 UTC, kate-lozovaya commented on packages/client/src/pages/Registration/Registration.tsx
> +      fields={omit(fieldsConfig, [
А может вообще убрать lodash получится?

2024-03-21 14:01 UTC, kate-lozovaya commented
У меня не было ответов утром, а сейчас они появились и по времени написаны раньше моих. Не знаю, почему так)
Остался толкьо вопрос по lodash. Он тут точно нуден? Может его убрать?

2024-03-21 14:48 UTC, ISAYwtf commented
> У меня не было ответов утром, а сейчас они появились и по времени написаны раньше моих. Не знаю, почему так) Остался толкьо вопрос по lodash. Он тут точно нуден? Может его убрать?

Убрать lodash из проекта в целом или конкретно в указанном месте?
Из проекта убирать не хотелось бы, иначе придется писать свои аналогичные функции, которые ничем отличаться не будут, особенно на таких необъемных данных. А время тратить на создание велосипеда не хочется))

2024-03-21 18:13 UTC, kate-lozovaya approved these changes

2024-03-22 17:07 UTC, merged