GCC-44 начало, конец игры, платформы и движение по ним
team-learning-yandex-praktikum/game-learning-project pull request #24
Opened 2024-03-29 08:09 UTC by LeylaBR

### Какую задачу решаем

### Скриншоты/видяшка (если есть)

### TBD (если есть)

2024-03-29 13:03 UTC, ISAYwtf commented on packages/client/src/pages/Game/Game.tsx
> +        return <PlayGame dispatch={dispatch} />
Здесь и ниже лучше передавать не `dispatch`, а функцию, которую он должен выполнить, например, если старт то 
`() => dispatch(gameActions.startGame())`

2024-03-29 13:08 UTC, ISAYwtf commented on packages/client/src/game-core/GameWorld.ts
> +    private dispatch: Dispatch
Вместо `dispatch` лучше передавать функцию, которую объект должен выполнить, например, если финиш то 
`finishGame: () => dispatch(gameActions.finishGame())`
а в месте использования `finishGame()`

Или как удобнее пропс назвать, но смысл такой

2024-03-29 13:40 UTC, ISAYwtf commented on packages/client/src/pages/Game/Game.tsx
> +    console.log(status)
Не забыть удалить лог

2024-03-29 17:50 UTC, ISAYwtf approved these changes

2024-03-29 19:39 UTC, IvanPeleshok requested changes
Замечательно потрудились
Есть оптимизация для колбеков, предусмотрели корнер кейсы с в возвратной функции из useEffect

Есть небольшие косметические замечания
Предлагаю поправить

Хорошего дня :)

2024-03-29 19:39 UTC, IvanPeleshok commented on packages/client/src/game-core/GameWorld.ts
> +            if (this.player.currState === 'Jump') {
Предлагаю избегать использования if в if-е
```
this.player.pos[1] < this.halfCanvasHeight 
&& this.player.currState === 'Jump'
```

Полагаю, что состояние игрока можно вынести в константы, чтобы переиспользовать
```
const PLAYER_STATE = {
  JUMP: 'Jump'
  ...
}

2024-03-29 19:39 UTC, IvanPeleshok commented on packages/client/src/game-core/GameWorld.ts
> +            this.player.fallPosition > 450 &&
450 / 500 предлагаю вынести в константы, чтобы было человекочитаемо (магические значения)

2024-03-29 19:39 UTC, IvanPeleshok commented on packages/client/src/game-core/GameWorld.ts
> +        for (let i = 0; i < numberOfPlatforms; i++) {
Наименование переменных должно быть человекочитаемо `i`

2024-03-29 19:39 UTC, IvanPeleshok commented on packages/client/src/game-core/GameWorld.ts
> +        this.context.fillStyle = 'white'
Возможно где-то ещё используется white?
Предлагаю вынести в константу

2024-03-29 19:39 UTC, IvanPeleshok commented on packages/client/src/pages/Game/Game.tsx
> +    if (status === 'finish') {
finish / game выносим в константу

2024-03-29 19:39 UTC, IvanPeleshok commented on packages/client/src/pages/Game/components/PlayGame/PlayGame.tsx
> +        if (status === 'game') {
Используем контанту

2024-03-29 19:39 UTC, IvanPeleshok commented on packages/client/src/store/game/gameSlice.ts
> +            state.status = 'game'
Используем контанты для game / finish

2024-03-31 09:23 UTC, IvanPeleshok approved these changes
Всё замечательно

Работа принята

Хорошего дня :)

2024-03-31 12:30 UTC, merged