GCC-20 - Реализована авторизация
team-learning-yandex-praktikum/game-learning-project pull request #9
Opened 2024-03-16 12:32 UTC by ISAYwtf

Реализован класс BaseApi на основе axios, предназначенный для создания классов апишек.
Реализована базовая аутентификация. Пока выноса в сервисы, так как в будущем добавим redux, а там и redux-thunk с redux-toolkit подтянутся.

2024-03-16 13:16 UTC, AnastasiaKurochkina approved these changes

2024-03-17 08:01 UTC, LeylaBR approved these changes

2024-03-17 08:21 UTC, IvanPeleshok requested changes
Добрый день!

Отлично поработали
Приятно удивили кастомными хуками, такое встречаю достаточно редко

Есть небольшие замечания, которые предлагаю доработать

Хорошего дня :)

2024-03-17 08:21 UTC, IvanPeleshok commented on packages/client/src/api/auth/index.ts
> +  async login(loginData: LoginDTO): Promise<void> {
login и logout возвращают `Promise<void>`, но есть сомнения, что data - void, предлагаю посмотреть повнимательнее

2024-03-17 08:21 UTC, IvanPeleshok commented on packages/client/src/api/auth/types.ts
> +  password: string
Такое ощущение, что нарушены отступы для простоты чтения 
```
extends ... {
  password: string

2024-03-17 08:21 UTC, IvanPeleshok commented on packages/client/src/api/baseApi/index.ts
> +    this.client = axios.create(baseConfig)
Здорово, что воспользовались настройкой экземпляра axios 👍

2024-03-17 08:21 UTC, IvanPeleshok commented on packages/client/src/utils/hooks/useAuthentication.ts
> +export const useCheckAuthentication = () => {
Было бы здорово декомпозировать хук в отдельный модуль

2024-03-17 08:21 UTC, IvanPeleshok commented on packages/client/src/utils/hooks/useAuthentication.ts
> +        console.log(data)
Точно ли необходима отладка?

2024-03-17 08:21 UTC, IvanPeleshok commented on packages/client/src/utils/hooks/useAuthentication.ts
> +    ;(async () => {
Самовызывающиеся функции сложны при чтении, предлагаю реализовать немного по-другому
```
useEffect(() => {
 ... 
 
 const fetchMe = async () => { ... }
 
 await fetchMe()
}, [deps])

2024-03-17 08:29 UTC, ISAYwtf commented on packages/client/src/api/auth/types.ts
> +  password: string
Отступы действительно нарушены, но тут дело в настройках проекта. lefthook автоматически исправляет все отступы под себя при коммите. Я пока не разбирался с этим из-за отсутствия времени дабы не сломать ничего в настройках

2024-03-17 08:31 UTC, ISAYwtf commented on packages/client/src/api/auth/index.ts
> +  async login(loginData: LoginDTO): Promise<void> {
Они возвращают 200 OK, разве это может быть хоть как-то использовано?

2024-03-17 08:34 UTC, ISAYwtf commented on packages/client/src/utils/hooks/useAuthentication.ts
> +        console.log(data)
В данном случае уже нет, спасибо за замечание

2024-03-17 08:41 UTC, ISAYwtf commented on packages/client/src/utils/hooks/useAuthentication.ts
> +    ;(async () => {
Поправил, только пришлось без `await` для `fetch`, так как `useEffect` принимает асинхронные функции, собственно поэтому самовызывающейся и воспользовался

2024-03-17 16:16 UTC, IvanPeleshok approved these changes
Поздравляю, апрув!
Работа выполнена отлично

2024-03-17 16:32 UTC, merged